version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - src/envs/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - app-data:/app

  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: always
    env_file:
      - src/envs/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"

   # TODO: Add RabbitMQ service

volumes:
  app-data:
    name: app-data
  postgres-data:
    name: postgres-data